services:
  - type: web
    name: tennis-app-backend
    env: node
    nodeVersion: 16.x
    buildCommand: node build.js
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://cotoirares05:<FwXcaqgu9hdIcVzj>@tennis.z8acxqp.mongodb.net/?retryWrites=true&w=majority&appName=tennis
      - key: JWT_SECRET
        value: your_jwt_secret_here 